### ISSUE TITLE
Updated codes to Python 3.6 showing error

### ISSUE THREAD

**Issue by executable16** [itspoma/audio-fingerprint-identifying-python#14]
@itspoma 

I forked this repo and updated the python files to Python 3.6.
But on running the command `make fingerprint-songs`

I get these errors.
```
Traceback (most recent call last):
  File "collect-fingerprints-of-songs.py", line 54, in <module>
    channel_hashes = set(channel_hashes)
  File "/home/executable/Desktop/audio-fingerprint-identifying-python/libs/fingerprint.py", line 168, in generate_hashes
    h = hashlib.sha1("%s|%s|%s" % (str(freq1), str(freq2), str(t_delta)))
TypeError: Unicode-objects must be encoded before hashing
sqlite - connection has been closed
make: *** [Makefile:19: fingerprint-songs] Error 1
```

**Comment by ryanhammonds** [comment]
In `fingerprint.py`, changing this in the line 167 (or 168 in your traceback) :
```
h = hashlib.sha1("%s|%s|%s" % (str(freq1), str(freq2), str(t_delta)))
```
to this:
```
hash_string = "%s|%s|%s" % (str(freq1), str(freq2), str(t_delta))
h = hashlib.sha1(hash_string.encode('utf-8'))
```
worked for me.

**Comment by executable16** [comment]
Great. You might run into another problem on running make recognize-listen
seconds=5.
If you fix that, it would be great however I have fixed that but I am just
unsure, if it's okay and legit.

**Comment by itspoma** [comment]
Thanks everyone! If you think that would help others, please create PR.

Cheers,
Roman

**Comment by ryanhammonds** [comment]
@executable16  want to work with me on a converting this to python3, refactoring for more standard python packages, adding functionality for users to upload their databases via aws, hosting via gh-pages, and updated related changes with doc and tests?

I would be cool to have an open source database where people can id their tracks without needing to create their own database, and also upload the names of ones that don't exist in the open database. It doesn't look like shazam has an api, spotify does, but I don't believe it's possible to query the fingerprint hashes.

My original idea was to use this packages to automatically ID tracks on long DJ sets (youtube: boiler room or cercle). But then realized and open source database would be needed.
