### ISSUE TITLE
Write a requirements.txt file

### ISSUE THREAD

**Issue by Naereen** [itspoma/audio-fingerprint-identifying-python#7]
Hi,
Nice projects :clap:!

It's hard to test though, as there is no clean list of dependencies (I had to try, see that module X is missing, run `pip install X`, then try again, like 5 times…).
Could you write a [`requirements.txt`](https://packaging.python.org/discussions/install-requires-vs-requirements/?highlight=requirements#requirements-files) please?
Thanks!

**Comment by Naereen** [comment]
Adding minimal versions should be usefull too.

**Comment by Theverat** [comment]
The requirements.txt is missing `matplotlib` (required by `make clean reset`).
